/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.toml --include-runtime=false worker/worker-configuration.d.ts` (hash: fab68877490653343b64e324e9623878)
interface __BaseEnv_Env {
	GEMINI_MODEL: "gemini-3.6-flash";
	ALLOWED_ORIGIN: "https://jinjinjin459.github.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
